version: "3.8"
services:
    app:
        image: node:16.13.2
        volumes:
            - .:/app
        environment:
            - TZ=Asia/Tokyo
        working_dir: /app
        command: "npm run start"
        ports:
            - '3000:3000'
    swagger_ui:
        image: swaggerapi/swagger-ui
        environment:
        - URL=http://localhost:3000/api-docs
        - DISPLAY_OPERATION_ID=true
        ports:
        - '8080:8080'